services:
  inovia-nutri-mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: inovia-nutri-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db